"use client";

import { useState, useEffect, useCallback, startTransition } from "react";
import { motion } from "framer-motion";
import { Sparkles, Pencil, RotateCcw, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { apiFetch } from "@/lib/api";

export function AICareerSummary() {
  const [summary, setSummary] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editText, setEditText] = useState("");
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const fetchSummary = useCallback(async () => {
    try {
      setLoading(true);
      setError("");
      const data = await apiFetch("/api/profile/career-summary");
      setSummary(data.summary ?? "");
      setIsAutoGenerated(data.is_auto_generated ?? false);
    } catch {
      setError("Failed to load summary");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    startTransition(() => { fetchSummary(); });
  }, [fetchSummary]);

  const handleSave = async () => {
    try {
      setSaving(true);
      setError("");
      await apiFetch("/api/profile/career-summary", {
        method: "PUT",
        body: JSON.stringify({ summary: editText }),
      });
      setSummary(editText);
      setIsAutoGenerated(false);
      setIsEditing(false);
    } catch {
      setError("Failed to save summary");
    } finally {
      setSaving(false);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard not available
    }
  };

  if (loading) {
    return (
      <div className="rounded-xl border border-border bg-bg-surface p-5">
        <div className="mb-3 h-4 w-16 animate-pulse rounded bg-bg-hover" />
        <div className="space-y-2">
          <div className="h-3 w-full animate-pulse rounded bg-bg-hover" />
          <div className="h-3 w-3/4 animate-pulse rounded bg-bg-hover" />
          <div className="h-3 w-1/2 animate-pulse rounded bg-bg-hover" />
        </div>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      className="group rounded-xl border border-border bg-bg-surface p-5 transition-all duration-200 hover:border-accent/20"
    >
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent/10 text-accent">
            <Sparkles className="h-4 w-4" />
          </div>
          <h3 className="font-mono text-xs font-medium uppercase tracking-widest text-fg-muted">About</h3>
          {isAutoGenerated && (
            <Badge tone="accent">AI-generated</Badge>
          )}
        </div>
        {!isEditing && summary && (
          <div className="flex items-center gap-1 opacity-0 transition-opacity duration-150 group-hover:opacity-100">
            <Button variant="ghost" size="sm" icon={<Pencil className="h-3.5 w-3.5" />} onClick={() => { setEditText(summary); setIsEditing(true); }}>
              Edit
            </Button>
            <Button variant="ghost" size="sm" icon={<RotateCcw className="h-3.5 w-3.5" />} onClick={fetchSummary}>
              Regenerate
            </Button>
            <Button variant="ghost" size="sm" icon={copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />} onClick={handleCopy}>
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
        )}
      </div>

      {error && <p className="mb-2 text-xs text-danger">{error}</p>}

      {isEditing ? (
        <div className="space-y-3">
          <textarea
            value={editText}
            onChange={(e) => setEditText(e.target.value)}
            className="w-full rounded-lg border border-border bg-bg-default px-3 py-2 text-sm text-fg-default placeholder:text-fg-subtle transition-all duration-150 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent-ring/50"
            rows={4}
          />
          <div className="flex gap-2">
            <Button size="sm" loading={saving} onClick={handleSave}>Save</Button>
            <Button variant="ghost" size="sm" onClick={() => setIsEditing(false)}>Cancel</Button>
          </div>
        </div>
      ) : summary ? (
        <p className="text-sm leading-relaxed text-fg-muted">{summary}</p>
      ) : (
        <p className="text-sm italic text-fg-subtle">No summary available. Click Regenerate to create one.</p>
      )}
    </motion.div>
  );
}
